### ISSUE TITLE
St. Joe Event Checklist

### ISSUE THREAD

**Issue by jhh** [strykeforce/rapidreact#66]
## Software Version Check
Confirm the required versions of the following are correct on the competition robot or driver stations as approriate.

- [x] Driver Station (3 laptops)
- [x] WPILib GradleRIO version in `build.gradle` ([link](https://github.com/wpilibsuite/allwpilib/releases))
- [x] `vendordeps/WPILibNewCommands.json`
- [x] `vendordeps/thirdcoast.json` ([link](https://github.com/strykeforce/thirdcoast/releases))
- [x] Deadeye Jetson software
- [x] Deadeye cloned SD-card images (2) 
- [x] `vendordeps/deadeye.json` ([link](https://github.com/strykeforce/deadeye/releases))
- [x] roboRIO
- [x] navX firmware ([link](https://www.kauailabs.com/navx-mxp/))
- [x] `vendordeps/navx_frc.json` ([link](https://www.kauailabs.com/dist/frc/2022/navx_frc.json))
- [x] CTRE firmware ([link](https://store.ctr-electronics.com/software/))
- [x] `vendordeps/Phoenix.json` ([link](https://maven.ctr-electronics.com/release/com/ctre/phoenix/Phoenix-frc2022-latest.json))
- [x] PDP firmware ([link](https://docs.revrobotics.com/rev-11-1850/software-resources/power-distribution-hub-firmware-changelog))
- [x] `vendordeps/REVLib.json` ([link](https://software-metadata.revrobotics.com/REVLib.json))

## Software Release

Create a GitHub release version and tag.

- [x] Pull requests merged or update milestone no next event
- [x] Robot Code
- [x] Shuffleboard config archived in robot repo
- [x] Deadeye pipeline config archived in robot repo
- [x] `README` hardware assignments up to date

## Packing Checklist

Pack the following items to take to event.

- [ ] ~Backup copy of all software releases (USB)~
- [x] Driver Station laptops (3)
- [x] Driver Station power supplies (3)
- [x] Laptop with Grapher (for fieldside pitting)
- [x] Controller case (2 controller sets)
- [ ] ~USB thumb drive~
- [x] Velcro measuring block
- [x] digital protractor
- [x] ethernet switch and 120v inverter
- [x] Grapher NUC, keyboard and mouse

### Cables

- [x] HDMI Cables (2)
- [x] ethernet short (4)
- [x] ethernet 25ft (1)
- [x] ethernet 100ft spool (1)
- [x] USB3 cables A and B

### Spare Parts

- [x] event interlock
- [x] roboRIO
- [x] navX
- [x] radio
- [x] Jetson Nano
- [x] Raspberry Pi camera (2)
- [x] Raspberry Pi camera ribbon cable (2)
- [x] camera LED driver block
- [x] camera LEDs
